# Generated by Django 5.1.15 on 2026-08-16 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='code')),
                ('libelle', models.CharField(max_length=100, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'domaine d’activité',
                'verbose_name_plural': 'domaines d’activité',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Succursale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='créée le')),
            ],
            options={
                'verbose_name': 'succursale',
                'verbose_name_plural': 'succursales',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('est_systeme', models.BooleanField(default=False, help_text='Un rôle système ne peut pas être supprimé.', verbose_name='rôle système')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'rôle',
                'verbose_name_plural': 'rôles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='compte')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('date_desactivation', models.DateTimeField(blank=True, help_text='Renseignée lors d’une désactivation (l’utilisateur n’est jamais supprimé).', null=True, verbose_name='date de désactivation')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('roles', models.ManyToManyField(blank=True, related_name='utilisateurs', to='core.role', verbose_name='rôles')),
            ],
            options={
                'verbose_name': 'profil utilisateur',
                'verbose_name_plural': 'profils utilisateurs',
                'ordering': ['compte'],
                'permissions': [('view_utilisateur', 'Peut consulter les utilisateurs'), ('create_utilisateur', 'Peut créer un utilisateur'), ('update_utilisateur', 'Peut modifier un utilisateur'), ('activate_utilisateur', 'Peut activer un utilisateur'), ('deactivate_utilisateur', 'Peut désactiver un utilisateur')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, verbose_name='module')),
                ('action', models.CharField(max_length=100, verbose_name='action')),
                ('objet_type', models.CharField(blank=True, max_length=100, verbose_name='type d’objet')),
                ('objet_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='id objet')),
                ('ancienne_valeur', models.JSONField(blank=True, null=True, verbose_name='ancienne valeur')),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True, verbose_name='nouvelle valeur')),
                ('motif', models.TextField(blank=True, verbose_name='motif')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('succursale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='core.succursale', verbose_name='succursale')),
            ],
            options={
                'verbose_name': 'trace d’audit',
                'verbose_name_plural': 'traces d’audit',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserSuccursale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principale', models.BooleanField(default=False, verbose_name='succursale principale')),
                ('date_affectation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='affecté le')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='core.domaine', verbose_name='domaine')),
                ('succursale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='core.succursale', verbose_name='succursale')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_succursales', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'affectation utilisateur / succursale',
                'verbose_name_plural': 'affectations utilisateurs / succursales',
                'unique_together': {('utilisateur', 'succursale', 'domaine')},
            },
        ),
    ]
