# Generated by Django 5.1.15 on 2026-08-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-date'], 'permissions': [('view_audit', 'Peut consulter les traces d’audit')], 'verbose_name': 'trace d’audit', 'verbose_name_plural': 'traces d’audit'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['nom'], 'permissions': [('create_role', 'Peut créer un rôle'), ('update_role', 'Peut modifier un rôle'), ('view_permission', 'Peut consulter les permissions')], 'verbose_name': 'rôle', 'verbose_name_plural': 'rôles'},
        ),
        migrations.AlterModelOptions(
            name='succursale',
            options={'ordering': ['nom'], 'permissions': [('create_succursale', 'Peut créer une succursale'), ('update_succursale', 'Peut modifier une succursale')], 'verbose_name': 'succursale', 'verbose_name_plural': 'succursales'},
        ),
    ]
