# Generated by Django 5.1.15 on 2026-08-16 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersuccursale',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Rôle exercé par l’utilisateur dans ce périmètre (succursale + domaine).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='core.role', verbose_name='rôle dans ce périmètre'),
        ),
    ]
