# Generated by Django 5.1.15 on 2026-08-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usersuccursale_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fonction',
            field=models.CharField(blank=True, help_text='Ex. : Magasinier, Caissière, Chef de cuisine…', max_length=150, verbose_name='fonction / service'),
        ),
    ]
