# Generated by Django 5.1.15 on 2026-08-17 16:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvisionnement', '0007_inventaire_unique_par_jour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'catégorie de menu',
                'verbose_name_plural': 'catégories de menu',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'salle',
                'verbose_name_plural': 'salles',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='numéro')),
                ('emporter', models.BooleanField(default=False, verbose_name='à emporter')),
                ('date_ouverture', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ouverture')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='clôture')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_PREPARATION', 'En préparation'), ('SERVIE', 'Servie'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='OUVERTE', max_length=16, verbose_name='statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('mode_paiement', models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('MOBILE', 'Mobile money'), ('CARTE', 'Carte')], max_length=12, verbose_name='mode de paiement')),
                ('stock_consomme', models.BooleanField(default=False, verbose_name='stock consommé')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_restauration', to=settings.AUTH_USER_MODEL, verbose_name='serveur')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plats', to='restauration.categoriemenu', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'plat',
                'verbose_name_plural': 'plats',
                'ordering': ['categorie__ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix unitaire')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='restauration.commande', verbose_name='commande')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commandes', to='restauration.plat', verbose_name='plat')),
            ],
            options={
                'verbose_name': 'ligne de commande',
                'verbose_name_plural': 'lignes de commande',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='numéro')),
                ('places', models.PositiveIntegerField(default=4, verbose_name='places')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='restauration.salle', verbose_name='salle')),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'tables',
                'ordering': ['salle__ordre', 'salle__nom', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='restauration.table', verbose_name='table'),
        ),
        migrations.CreateModel(
            name='CompositionPlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(help_text='Quantité d’article consommée pour une portion du plat.', verbose_name='quantité')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compositions_plats', to='approvisionnement.article', verbose_name='article')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='restauration.plat', verbose_name='plat')),
            ],
            options={
                'verbose_name': 'composition de plat',
                'verbose_name_plural': 'compositions de plat',
                'constraints': [models.UniqueConstraint(fields=('plat', 'article'), name='composition_unique_plat_article')],
            },
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('salle', 'numero'), name='table_unique_par_salle'),
        ),
    ]
