# Generated by Django 5.1.15 on 2026-08-17 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrer_workflow(apps, schema_editor):
    Commande = apps.get_model('restauration', 'Commande')
    Imprimante = apps.get_model('restauration', 'Imprimante')
    Commande.objects.filter(statut='EN_PREPARATION').update(statut='VALIDEE')
    Imprimante.objects.get_or_create(
        nom='Cuisine',
        defaults={'service': 'CUISINE', 'nom_systeme': 'Cuisine'},
    )
    Imprimante.objects.get_or_create(
        nom='Bar',
        defaults={'service': 'BAR', 'nom_systeme': 'Bar'},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('restauration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imprimante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('service', models.CharField(choices=[('CUISINE', 'Cuisine'), ('BAR', 'Bar')], max_length=10, verbose_name='service')),
                ('nom_systeme', models.CharField(help_text='Nom de l’imprimante telle qu’elle apparaît sur le poste (cuisine ou bar).', max_length=150, verbose_name='nom de l’imprimante')),
            ],
            options={
                'verbose_name': 'imprimante',
                'verbose_name_plural': 'imprimantes',
                'ordering': ['service', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='annulee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_annulees', to=settings.AUTH_USER_MODEL, verbose_name='annulée par'),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date d’annulation'),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de validation'),
        ),
        migrations.AddField(
            model_name='commande',
            name='motif_annulation',
            field=models.CharField(blank=True, max_length=250, verbose_name='motif d’annulation'),
        ),
        migrations.AddField(
            model_name='commande',
            name='reference_bon',
            field=models.CharField(blank=True, help_text='Obligatoire si la commande est saisie à partir d’un bon papier.', max_length=50, verbose_name='référence du bon papier'),
        ),
        migrations.AddField(
            model_name='commande',
            name='serveur',
            field=models.CharField(blank=True, max_length=150, verbose_name='serveur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='source',
            field=models.CharField(choices=[('TABLETTE', 'Tablette'), ('BON_PAPIER', 'Bon papier')], default='TABLETTE', max_length=12, verbose_name='saisie'),
        ),
        migrations.AddField(
            model_name='commande',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_validees', to=settings.AUTH_USER_MODEL, verbose_name='validée par'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='date_service',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de service'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='imprimante_nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='imprimante'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='servi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_servies', to=settings.AUTH_USER_MODEL, verbose_name='servi par'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='service',
            field=models.CharField(blank=True, choices=[('CUISINE', 'Cuisine'), ('BAR', 'Bar')], max_length=10, verbose_name='destination'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SERVIE', 'Servie'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=12, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='stock_consomme',
            field=models.BooleanField(default=False, verbose_name='stock consommé'),
        ),
        migrations.AddField(
            model_name='plat',
            name='service',
            field=models.CharField(choices=[('CUISINE', 'Cuisine'), ('BAR', 'Bar')], default='CUISINE', help_text='Cuisine ou bar : détermine où la ligne s’affiche après validation.', max_length=10, verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('OUVERTE', 'Saisie'), ('VALIDEE', 'Validée'), ('SERVIE', 'Servie'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='OUVERTE', max_length=16, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_restauration', to=settings.AUTH_USER_MODEL, verbose_name='opérateur'),
        ),
        migrations.AddField(
            model_name='plat',
            name='imprimante',
            field=models.ForeignKey(help_text='Imprimante du service qui recevra le ticket de ce plat.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plats', to='restauration.imprimante', verbose_name='imprimante'),
        ),
        migrations.RunPython(migrer_workflow, migrations.RunPython.noop),
    ]
