# Generated by Django 5.1.15 on 2026-08-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauration', '0002_imprimante_commande_annulee_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='devise',
            field=models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='CDF', max_length=3, verbose_name='devise'),
        ),
        migrations.AddField(
            model_name='plat',
            name='devise',
            field=models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='CDF', max_length=3, verbose_name='devise'),
        ),
        migrations.AddField(
            model_name='plat',
            name='quantite',
            field=models.PositiveIntegerField(default=0, help_text='Augmentée par les sorties magasin vers la cuisine ou le bar, diminuée à la commande.', verbose_name='quantité disponible'),
        ),
        migrations.AddField(
            model_name='plat',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=2, help_text='Un signal s’affiche quand il ne reste plus que ce nombre de portions.', verbose_name='seuil d’alerte'),
        ),
    ]
