# Generated by Django 5.1.15 on 2026-08-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauration', '0003_lignecommande_devise_plat_devise_plat_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='quantite',
            field=models.PositiveIntegerField(default=0, help_text='Bar : augmentée automatiquement par les sorties magasin. Cuisine : saisie des portions préparées sur l’écran Cuisine. Diminuée à la commande.', verbose_name='quantité disponible'),
        ),
    ]
