# Generated by Django 5.1.15 on 2026-08-17 17:51

from django.db import migrations, models


def copier_description_plats(apps, schema_editor):
    LigneCommande = apps.get_model('restauration', 'LigneCommande')
    for ligne in LigneCommande.objects.select_related('plat'):
        if ligne.plat_id and not ligne.designation:
            ligne.designation = ligne.plat.nom
            ligne.description_plat = ligne.plat.description
            ligne.save(update_fields=['designation', 'description_plat'])


class Migration(migrations.Migration):

    dependencies = [
        ('restauration', '0004_alter_plat_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='description_plat',
            field=models.TextField(blank=True, help_text='Description enregistrée au moment de la commande.', verbose_name='description du plat'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='designation',
            field=models.CharField(blank=True, help_text='Libellé du plat au moment de la commande.', max_length=150, verbose_name='plat commandé'),
        ),
        migrations.RunPython(copier_description_plats, migrations.RunPython.noop),
    ]
