# Generated by Django 5.1.15 on 2026-09-01 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restauration', '0010_stock_a_validation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_ouverture'], 'permissions': [('view_restauration', 'Peut consulter la restauration'), ('create_commande', 'Peut enregistrer une commande'), ('modify_commande', 'Peut modifier une commande avant validation'), ('validate_commande', 'Peut valider et imprimer une commande'), ('cancel_commande', 'Peut annuler une commande non validée'), ('encaisser_commande', 'Peut enregistrer le paiement d’une commande'), ('servir_ligne', 'Peut marquer une ligne comme servie'), ('adjust_plat_portions', 'Peut ajouter des plats préparés (cuisine / barbecus)')], 'verbose_name': 'commande', 'verbose_name_plural': 'commandes'},
        ),
    ]
