# Generated by Django 5.1.15 on 2026-08-18 18:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_user_fonction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieImmobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'catégorie d’immobilisation',
                'verbose_name_plural': 'catégories d’immobilisations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Immobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='code')),
                ('designation', models.CharField(max_length=200, verbose_name='désignation')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='numéro de série')),
                ('valeur_acquisition', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='valeur d’acquisition')),
                ('date_acquisition', models.DateField(blank=True, null=True, verbose_name='date d’acquisition')),
                ('fournisseur', models.CharField(blank=True, max_length=150, verbose_name='fournisseur')),
                ('etat_physique', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon'), ('A_REPARER', 'À réparer'), ('CASSE', 'Casse')], default='NEUF', max_length=12, verbose_name='état physique')),
                ('statut_administratif', models.CharField(choices=[('STOCKE', 'Stocké'), ('EN_SERVICE', 'En service'), ('EN_REPARATION', 'En réparation'), ('DECLASSE', 'Déclassé')], default='STOCKE', max_length=14, verbose_name='statut administratif')),
                ('service', models.CharField(blank=True, max_length=150, verbose_name='service')),
                ('emplacement', models.CharField(blank=True, max_length=150, verbose_name='emplacement')),
                ('observation', models.TextField(blank=True, verbose_name='observation')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='immobilisations', to='immobilisations.categorieimmobilisation', verbose_name='catégorie')),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='immobilisations', to='core.domaine', verbose_name='domaine d’activité')),
                ('succursale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='immobilisations', to='core.succursale', verbose_name='succursale')),
            ],
            options={
                'verbose_name': 'immobilisation',
                'verbose_name_plural': 'immobilisations',
                'ordering': ['code'],
                'permissions': [('view_asset', 'Peut consulter les immobilisations'), ('create_asset', 'Peut créer une immobilisation'), ('update_asset', 'Peut modifier une immobilisation'), ('assign_asset', 'Peut affecter une immobilisation'), ('move_asset', 'Peut déplacer une immobilisation'), ('repair_asset', 'Peut gérer les réparations'), ('report_damage_asset', 'Peut déclarer une casse'), ('decommission_asset', 'Peut déclasser une immobilisation')],
            },
        ),
        migrations.CreateModel(
            name='Deplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_service', models.CharField(blank=True, max_length=150, verbose_name='ancien service')),
                ('nouveau_service', models.CharField(blank=True, max_length=150, verbose_name='nouveau service')),
                ('ancien_emplacement', models.CharField(blank=True, max_length=150, verbose_name='ancien emplacement')),
                ('nouvel_emplacement', models.CharField(blank=True, max_length=150, verbose_name='nouvel emplacement')),
                ('date_deplacement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de déplacement')),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='motif')),
                ('ancienne_succursale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.succursale', verbose_name='ancienne succursale')),
                ('nouvelle_succursale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.succursale', verbose_name='nouvelle succursale')),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deplacements_immobilisations', to=settings.AUTH_USER_MODEL, verbose_name='par')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deplacements', to='immobilisations.immobilisation', verbose_name='immobilisation')),
            ],
            options={
                'verbose_name': 'déplacement',
                'verbose_name_plural': 'déplacements',
                'ordering': ['-date_deplacement'],
            },
        ),
        migrations.CreateModel(
            name='Declassement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now, verbose_name='demande le')),
                ('motif', models.CharField(max_length=200, verbose_name='motif')),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demande'), ('VALIDE', 'Validé')], default='DEMANDE', max_length=10, verbose_name='statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='validé le')),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declassements_demandes', to=settings.AUTH_USER_MODEL, verbose_name='demandé par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declassements_valides', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declassements', to='immobilisations.immobilisation', verbose_name='immobilisation')),
            ],
            options={
                'verbose_name': 'déclassement',
                'verbose_name_plural': 'déclassements',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Casse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_casse', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('motif', models.CharField(max_length=200, verbose_name='motif')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('decision', models.CharField(blank=True, choices=[('REPARABLE', 'Réparable'), ('REMPLACEMENT', 'Remplacement'), ('DECLASSEMENT', 'Déclassement')], max_length=14, null=True, verbose_name='décision')),
                ('observation', models.TextField(blank=True, verbose_name='observation')),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casses_immobilisations', to=settings.AUTH_USER_MODEL, verbose_name='par')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casses', to='immobilisations.immobilisation', verbose_name='immobilisation')),
            ],
            options={
                'verbose_name': 'casse',
                'verbose_name_plural': 'casses',
                'ordering': ['-date_casse'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=150, verbose_name='service')),
                ('emplacement', models.CharField(blank=True, max_length=150, verbose_name='emplacement')),
                ('date_affectation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date d’affectation')),
                ('actif', models.BooleanField(default=True, verbose_name='active')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_immobilisations', to=settings.AUTH_USER_MODEL, verbose_name='par')),
                ('succursale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_immobilisations', to='core.succursale', verbose_name='succursale')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='immobilisations.immobilisation', verbose_name='immobilisation')),
            ],
            options={
                'verbose_name': 'affectation',
                'verbose_name_plural': 'affectations',
                'ordering': ['-date_affectation'],
            },
        ),
        migrations.CreateModel(
            name='Reparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reparation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('motif', models.CharField(max_length=200, verbose_name='motif')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('cout', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='coût')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='EN_COURS', max_length=10, verbose_name='statut')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparations', to='immobilisations.immobilisation', verbose_name='immobilisation')),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reparations_immobilisations', to=settings.AUTH_USER_MODEL, verbose_name='par')),
            ],
            options={
                'verbose_name': 'réparation',
                'verbose_name_plural': 'réparations',
                'ordering': ['-date_reparation'],
            },
        ),
    ]
