# Generated by Django 5.1.15 on 2026-08-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0004_service_emplacement_convert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='immobilisation',
            options={'ordering': ['code'], 'permissions': [('view_asset', 'Peut consulter les immobilisations'), ('create_asset', 'Peut créer une immobilisation'), ('update_asset', 'Peut modifier une immobilisation'), ('assign_asset', 'Peut affecter une immobilisation'), ('move_asset', 'Peut déplacer une immobilisation'), ('repair_asset', 'Peut gérer les réparations'), ('report_damage_asset', 'Peut déclarer une casse'), ('decommission_asset', 'Peut déclasser une immobilisation'), ('view_declassified_asset', 'Peut consulter les biens déclassés')], 'verbose_name': 'immobilisation', 'verbose_name_plural': 'immobilisations'},
        ),
    ]
