# Generated by Django 5.1.15 on 2026-08-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0005_alter_immobilisation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='casse',
            name='responsable_dommage',
            field=models.CharField(blank=True, help_text='Nom de la personne ayant causé le dommage.', max_length=150, verbose_name='responsable du dommage'),
        ),
    ]
