# Generated by Django 5.1.15 on 2026-08-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0006_casse_responsable_dommage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casse',
            name='responsable_dommage',
            field=models.CharField(blank=True, max_length=150, verbose_name='responsable du dommage'),
        ),
    ]
