# Generated by Django 5.1.15 on 2026-08-25 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def valider_biens_existants(apps, schema_editor):
    """Les biens déjà en base étaient en usage : on les considère validés."""
    Immobilisation = apps.get_model('immobilisations', 'Immobilisation')
    Immobilisation.objects.filter(statut_validation='BROUILLON').update(
        statut_validation='VALIDE')


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0007_alter_casse_responsable_dommage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='immobilisation',
            options={'ordering': ['code'], 'permissions': [('view_asset', 'Peut consulter les immobilisations'), ('create_asset', 'Peut créer une immobilisation'), ('update_asset', 'Peut modifier une immobilisation'), ('assign_asset', 'Peut affecter une immobilisation'), ('move_asset', 'Peut déplacer une immobilisation'), ('repair_asset', 'Peut gérer les réparations'), ('report_damage_asset', 'Peut déclarer une casse'), ('decommission_asset', 'Peut déclasser une immobilisation'), ('view_declassified_asset', 'Peut consulter les biens déclassés'), ('validate_asset', 'Peut valider une immobilisation')], 'verbose_name': 'immobilisation', 'verbose_name_plural': 'immobilisations'},
        ),
        migrations.AddField(
            model_name='immobilisation',
            name='date_soumission',
            field=models.DateTimeField(blank=True, null=True, verbose_name='soumis le'),
        ),
        migrations.AddField(
            model_name='immobilisation',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='validé le'),
        ),
        migrations.AddField(
            model_name='immobilisation',
            name='duree_vie',
            field=models.PositiveIntegerField(blank=True, help_text='Durée prévue d’utilisation en années (facultatif).', null=True, verbose_name='durée de vie (années)'),
        ),
        migrations.AddField(
            model_name='immobilisation',
            name='motif_rejet',
            field=models.CharField(blank=True, max_length=300, verbose_name='motif de rejet'),
        ),
        migrations.AddField(
            model_name='immobilisation',
            name='periode_entretien',
            field=models.PositiveIntegerField(blank=True, help_text='Fréquence d’entretien en mois (facultatif).', null=True, verbose_name='période d’entretien (mois)'),
        ),
        migrations.AddField(
            model_name='immobilisation',
            name='soumis_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens_soumis', to=settings.AUTH_USER_MODEL, verbose_name='soumis par'),
        ),
        migrations.AddField(
            model_name='immobilisation',
            name='statut_validation',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=12, verbose_name='validation'),
        ),
        migrations.AddField(
            model_name='immobilisation',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens_valides', to=settings.AUTH_USER_MODEL, verbose_name='validé par'),
        ),
        migrations.RunPython(valider_biens_existants, migrations.RunPython.noop),
    ]
