# Generated by Django 5.1.15 on 2026-08-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilisations', '0008_alter_immobilisation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immobilisation',
            name='fournisseur',
        ),
        migrations.AddField(
            model_name='casse',
            name='date_dommage',
            field=models.DateField(blank=True, help_text='Date à laquelle le dommage est survenu (facultatif).', null=True, verbose_name='date du dommage'),
        ),
    ]
