# Generated by Django 5.1.15 on 2026-08-14 17:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'acteur',
                'verbose_name_plural': 'acteurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('designation', models.CharField(max_length=200, verbose_name='désignation')),
                ('seuil_minimum', models.PositiveIntegerField(default=0, verbose_name='seuil minimum')),
                ('stock', models.IntegerField(default=0, verbose_name='stock')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
            ],
            options={
                'verbose_name': 'fournisseur',
                'verbose_name_plural': 'fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('libelle', models.CharField(max_length=50, verbose_name='libellé')),
            ],
            options={
                'verbose_name': 'unité',
                'verbose_name_plural': 'unités',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AlerteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('seuil', models.PositiveIntegerField(verbose_name='seuil')),
                ('date_alerte', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='approvisionnement.article', verbose_name='article')),
            ],
            options={
                'verbose_name': 'alerte stock',
                'verbose_name_plural': 'alertes stock',
                'ordering': ['-date_alerte'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='approvisionnement.categorie', verbose_name='catégorie'),
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inventaire', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé')], default='BROUILLON', max_length=12, verbose_name='statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventaires', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
            ],
            options={
                'verbose_name': 'inventaire',
                'verbose_name_plural': 'inventaires',
                'ordering': ['-date_inventaire'],
            },
        ),
        migrations.CreateModel(
            name='Fonctionnalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('libelle', models.CharField(max_length=150, verbose_name='fonctionnalité')),
                ('comportement_attendu', models.TextField(verbose_name='comportement attendu')),
                ('donnees_principales', models.TextField(verbose_name='données principales')),
                ('regles_gestion', models.TextField(verbose_name='règles de gestion')),
                ('priorite', models.CharField(blank=True, max_length=50, verbose_name='priorité')),
                ('acteurs', models.ManyToManyField(related_name='fonctionnalites', to='approvisionnement.acteur', verbose_name='acteurs')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fonctionnalites', to='approvisionnement.module', verbose_name='module')),
            ],
            options={
                'verbose_name': 'fonctionnalité',
                'verbose_name_plural': 'fonctionnalités',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement')], max_length=12, verbose_name='type')),
                ('quantite', models.IntegerField(verbose_name='quantité')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='motif')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='destination')),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('valide', models.BooleanField(default=False, verbose_name='validé')),
                ('autorisation_depassement', models.BooleanField(default=False, help_text='Autorise une sortie au-delà du stock disponible.', verbose_name='autorisation de dépassement')),
                ('stock_avant', models.IntegerField(blank=True, null=True, verbose_name='stock avant')),
                ('stock_apres', models.IntegerField(blank=True, null=True, verbose_name='stock après')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='approvisionnement.article', verbose_name='article')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees', to='approvisionnement.fournisseur', verbose_name='fournisseur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='approvisionnement.unite', verbose_name='unité'),
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_systeme', models.IntegerField(verbose_name='stock système')),
                ('stock_physique', models.IntegerField(verbose_name='stock physique')),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='motif')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_inventaire', to='approvisionnement.article', verbose_name='article')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='approvisionnement.inventaire', verbose_name='inventaire')),
                ('mouvement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligne_inventaire', to='approvisionnement.mouvementstock', verbose_name='mouvement d’ajustement')),
            ],
            options={
                'verbose_name': 'ligne d’inventaire',
                'verbose_name_plural': 'lignes d’inventaire',
                'unique_together': {('inventaire', 'article')},
            },
        ),
    ]
