# Generated by Django 5.1.15 on 2026-08-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='nombre_portions',
            field=models.PositiveIntegerField(default=0, help_text='Mettre une valeur supérieure à 0 pour les vivres frais (poisson, poulet, etc.). Un champ portions sera alors demandé à la sortie.', verbose_name='nombre de portions'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='nombre_portions',
            field=models.PositiveIntegerField(default=0, help_text='Renseigné à la sortie pour les vivres frais (poisson, poulet, etc.).', verbose_name='nombre de portions'),
        ),
    ]
