# Generated by Django 5.1.15 on 2026-08-14 23:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0002_categorie_nombre_portions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='numéro')),
                ('date_approvisionnement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé')], default='BROUILLON', max_length=12, verbose_name='statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_approvisionnement', to='approvisionnement.fournisseur', verbose_name='fournisseur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_approvisionnement', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'bon d’approvisionnement',
                'verbose_name_plural': 'bons d’approvisionnement',
                'ordering': ['-date_approvisionnement'],
            },
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='bon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='approvisionnement.bonapprovisionnement', verbose_name='bon d’approvisionnement'),
        ),
        migrations.CreateModel(
            name='LigneApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='quantité')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_approvisionnement', to='approvisionnement.article', verbose_name='article')),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='approvisionnement.bonapprovisionnement', verbose_name='bon d’approvisionnement')),
                ('mouvement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligne_approvisionnement', to='approvisionnement.mouvementstock', verbose_name='mouvement d’entrée')),
            ],
            options={
                'verbose_name': 'ligne d’approvisionnement',
                'verbose_name_plural': 'lignes d’approvisionnement',
            },
        ),
    ]
