# Generated by Django 5.1.15 on 2026-08-14 23:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0003_bon_approvisionnement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='numéro')),
                ('date_sortie', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('motif', models.CharField(max_length=200, verbose_name='motif')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='destination')),
                ('autorisation_depassement', models.BooleanField(default=False, help_text='Autorise une sortie au-delà du stock disponible.', verbose_name='autorisation de dépassement')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé')], default='BROUILLON', max_length=12, verbose_name='statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_sortie', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'bon de sortie',
                'verbose_name_plural': 'bons de sortie',
                'ordering': ['-date_sortie'],
            },
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='bon_sortie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='approvisionnement.bonsortie', verbose_name='bon de sortie'),
        ),
        migrations.CreateModel(
            name='LigneSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='quantité')),
                ('nombre_portions', models.PositiveIntegerField(default=0, verbose_name='nombre de portions')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_sortie', to='approvisionnement.article', verbose_name='article')),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='approvisionnement.bonsortie', verbose_name='bon de sortie')),
                ('mouvement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligne_sortie', to='approvisionnement.mouvementstock', verbose_name='mouvement de sortie')),
            ],
            options={
                'verbose_name': 'ligne de sortie',
                'verbose_name_plural': 'lignes de sortie',
            },
        ),
    ]
