# Generated by Django 5.1.15 on 2026-08-14 23:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def recopier_historique(apps, schema_editor):
    BonApprovisionnement = apps.get_model('approvisionnement', 'BonApprovisionnement')
    BonSortie = apps.get_model('approvisionnement', 'BonSortie')
    Approvisionnement = apps.get_model('approvisionnement', 'Approvisionnement')
    ApprovisionnementLigne = apps.get_model('approvisionnement', 'ApprovisionnementLigne')

    for bon in BonApprovisionnement.objects.filter(statut='VALIDE'):
        if Approvisionnement.objects.filter(numero=bon.numero).exists():
            continue
        journal = Approvisionnement.objects.create(
            numero=bon.numero,
            type_operation='ENTREE',
            date_operation=bon.date_approvisionnement,
            fournisseur_id=bon.fournisseur_id,
            reference=bon.reference,
            commentaire=bon.commentaire,
            utilisateur_id=bon.utilisateur_id,
            bon_entree_id=bon.pk,
        )
        for ligne in bon.lignes.all():
            stock_avant = None
            stock_apres = None
            if ligne.mouvement_id:
                stock_avant = ligne.mouvement.stock_avant
                stock_apres = ligne.mouvement.stock_apres
            ApprovisionnementLigne.objects.create(
                approvisionnement=journal,
                article_id=ligne.article_id,
                quantite=ligne.quantite,
                stock_avant=stock_avant,
                stock_apres=stock_apres,
                mouvement_id=ligne.mouvement_id,
            )

    for bon in BonSortie.objects.filter(statut='VALIDE'):
        if Approvisionnement.objects.filter(numero=bon.numero).exists():
            continue
        journal = Approvisionnement.objects.create(
            numero=bon.numero,
            type_operation='SORTIE',
            date_operation=bon.date_sortie,
            motif=bon.motif,
            destination=bon.destination,
            commentaire=bon.commentaire,
            utilisateur_id=bon.utilisateur_id,
            bon_sortie_id=bon.pk,
        )
        for ligne in bon.lignes.all():
            stock_avant = None
            stock_apres = None
            if ligne.mouvement_id:
                stock_avant = ligne.mouvement.stock_avant
                stock_apres = ligne.mouvement.stock_apres
            ApprovisionnementLigne.objects.create(
                approvisionnement=journal,
                article_id=ligne.article_id,
                quantite=ligne.quantite,
                nombre_portions=ligne.nombre_portions,
                stock_avant=stock_avant,
                stock_apres=stock_apres,
                mouvement_id=ligne.mouvement_id,
            )


def vider_historique(apps, schema_editor):
    Approvisionnement = apps.get_model('approvisionnement', 'Approvisionnement')
    Approvisionnement.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0004_bon_sortie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='numéro')),
                ('type_operation', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=12, verbose_name='type')),
                ('date_operation', models.DateTimeField(verbose_name='date')),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='motif')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='destination')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('date_enregistrement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='enregistré le')),
                ('bon_entree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to='approvisionnement.bonapprovisionnement', verbose_name='bon d’entrée')),
                ('bon_sortie', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to='approvisionnement.bonsortie', verbose_name='bon de sortie')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_approvisionnement', to='approvisionnement.fournisseur', verbose_name='fournisseur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiques_approvisionnement', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'approvisionnement',
                'verbose_name_plural': 'approvisionnements',
                'ordering': ['-date_operation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovisionnementLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='quantité')),
                ('nombre_portions', models.PositiveIntegerField(default=0, verbose_name='nombre de portions')),
                ('stock_avant', models.IntegerField(blank=True, null=True, verbose_name='stock avant')),
                ('stock_apres', models.IntegerField(blank=True, null=True, verbose_name='stock après')),
                ('approvisionnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='approvisionnement.approvisionnement', verbose_name='approvisionnement')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_journal_approvisionnement', to='approvisionnement.article', verbose_name='article')),
                ('mouvement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligne_journal', to='approvisionnement.mouvementstock', verbose_name='mouvement')),
            ],
            options={
                'verbose_name': 'ligne d’historique d’approvisionnement',
                'verbose_name_plural': 'lignes d’historique d’approvisionnement',
            },
        ),
        migrations.RunPython(recopier_historique, vider_historique),
    ]
