# Generated by Django 5.1.15 on 2026-08-16 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0006_service_destination'),
        ('core', '0002_alter_auditlog_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvisionnement',
            options={'ordering': ['-date_operation', '-id'], 'permissions': [('create_approvisionnement', 'Peut créer une entrée de stock'), ('validate_approvisionnement', 'Peut valider une entrée de stock'), ('view_sortie', 'Peut consulter les sorties'), ('create_sortie', 'Peut créer une sortie de stock'), ('validate_sortie', 'Peut valider une sortie de stock'), ('view_historique', 'Peut consulter l’historique')], 'verbose_name': 'approvisionnement', 'verbose_name_plural': 'approvisionnements'},
        ),
        migrations.AlterModelOptions(
            name='inventaire',
            options={'ordering': ['-date_inventaire'], 'permissions': [('create_inventaire', 'Peut créer un inventaire'), ('validate_inventaire', 'Peut valider un inventaire')], 'verbose_name': 'inventaire', 'verbose_name_plural': 'inventaires'},
        ),
        migrations.AddField(
            model_name='approvisionnement',
            name='succursale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_approvisionnement', to='core.succursale', verbose_name='succursale'),
        ),
        migrations.AddField(
            model_name='article',
            name='succursale',
            field=models.ForeignKey(blank=True, help_text='Le stock est propre à la succursale : un même code peut exister dans plusieurs succursales avec des quantités différentes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='core.succursale', verbose_name='succursale'),
        ),
        migrations.AddField(
            model_name='bonapprovisionnement',
            name='succursale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bons_approvisionnement', to='core.succursale', verbose_name='succursale'),
        ),
        migrations.AddField(
            model_name='bonsortie',
            name='succursale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bons_sortie', to='core.succursale', verbose_name='succursale'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='succursale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventaires', to='core.succursale', verbose_name='succursale'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='succursale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='core.succursale', verbose_name='succursale'),
        ),
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(max_length=50, verbose_name='code'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('code', 'succursale')},
        ),
    ]
