# Generated by Django 5.1.15 on 2026-08-16 22:38

from django.conf import settings
from django.db import migrations, models


def dedupliquer_inventaires(apps, schema_editor):
    Inventaire = apps.get_model('approvisionnement', 'Inventaire')
    vus = set()
    for inventaire in Inventaire.objects.order_by('-id'):
        if inventaire.date_inventaire in vus:
            inventaire.delete()
        else:
            vus.add(inventaire.date_inventaire)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('approvisionnement', '0006_service_destination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupliquer_inventaires, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='inventaire',
            constraint=models.UniqueConstraint(
                fields=('date_inventaire',),
                name='inventaire_unique_par_jour',
            ),
        ),
    ]
