# Generated by Django 5.1.15 on 2026-08-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0007_alter_approvisionnement_options_and_more'),
        ('core', '0002_alter_auditlog_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='approvisionnement',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_approvisionnement', to='core.domaine', verbose_name='domaine d’activité'),
        ),
        migrations.AddField(
            model_name='article',
            name='domaine',
            field=models.ForeignKey(blank=True, help_text='Le stock est également propre au domaine d’activité (ex. BOUTIQUE).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='core.domaine', verbose_name='domaine d’activité'),
        ),
        migrations.AddField(
            model_name='bonapprovisionnement',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bons_approvisionnement', to='core.domaine', verbose_name='domaine d’activité'),
        ),
        migrations.AddField(
            model_name='bonsortie',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bons_sortie', to='core.domaine', verbose_name='domaine d’activité'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventaires', to='core.domaine', verbose_name='domaine d’activité'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='core.domaine', verbose_name='domaine d’activité'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('code', 'succursale', 'domaine')},
        ),
    ]
