# Generated by Django 5.1.15 on 2026-09-01 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0008_rename_article_produit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonapprovisionnement',
            options={'ordering': ['-date_approvisionnement'], 'permissions': [('view_approvisionnement', 'Peut consulter les approvisionnements'), ('create_approvisionnement', 'Peut enregistrer une entrée en stock'), ('validate_approvisionnement', 'Peut valider une entrée en stock'), ('cancel_approvisionnement', 'Peut annuler une entrée en stock'), ('view_rapport_approvisionnement', 'Peut consulter les rapports d’approvisionnement')], 'verbose_name': 'bon d’approvisionnement', 'verbose_name_plural': 'bons d’approvisionnement'},
        ),
        migrations.AlterModelOptions(
            name='bonsortie',
            options={'ordering': ['-date_sortie'], 'permissions': [('view_sortie', 'Peut consulter les sorties de stock'), ('create_sortie', 'Peut enregistrer une sortie de stock'), ('validate_sortie', 'Peut valider une sortie de stock'), ('cancel_sortie', 'Peut annuler une sortie de stock')], 'verbose_name': 'bon de sortie', 'verbose_name_plural': 'bons de sortie'},
        ),
        migrations.AlterModelOptions(
            name='inventaire',
            options={'ordering': ['-date_inventaire'], 'permissions': [('create_inventaire', 'Peut créer un inventaire'), ('validate_inventaire', 'Peut valider un inventaire')], 'verbose_name': 'inventaire', 'verbose_name_plural': 'inventaires'},
        ),
    ]
