# Generated by Django 5.1.15 on 2026-08-20 23:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restauration', '0010_stock_a_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(max_length=150, verbose_name='nom de la société')),
                ('sigle', models.CharField(blank=True, max_length=40, verbose_name='sigle')),
                ('logo', models.ImageField(blank=True, upload_to='etablissement/', verbose_name='logo')),
                ('contact', models.CharField(blank=True, max_length=80, verbose_name='contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('imprimante_caisse', models.CharField(blank=True, help_text='Nom Windows de l’imprimante 80 mm qui imprime le reçu client.', max_length=150, verbose_name='imprimante caisse')),
                ('message_recu', models.CharField(blank=True, default='Merci de votre visite', max_length=200, verbose_name='message du reçu')),
            ],
            options={
                'verbose_name': 'établissement',
                'verbose_name_plural': 'établissement',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='numéro')),
                ('date_facture', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE', 'Mobile money'), ('CARTE', 'Carte')], max_length=12, verbose_name='mode de paiement')),
                ('table_liberee', models.CharField(blank=True, max_length=150, verbose_name='table libérée')),
                ('nom_societe', models.CharField(max_length=150, verbose_name='société')),
                ('sigle', models.CharField(blank=True, max_length=40, verbose_name='sigle')),
                ('contact', models.CharField(blank=True, max_length=80, verbose_name='contact')),
                ('adresse', models.CharField(blank=True, max_length=250, verbose_name='adresse')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='restauration.commande', verbose_name='commande')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to=settings.AUTH_USER_MODEL, verbose_name='caissier')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150, verbose_name='désignation')),
                ('quantite', models.PositiveIntegerField(verbose_name='quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix unitaire')),
                ('devise', models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='CDF', max_length=3, verbose_name='devise')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture', verbose_name='facture')),
            ],
            options={
                'verbose_name': 'ligne de facture',
                'verbose_name_plural': 'lignes de facture',
                'ordering': ['id'],
            },
        ),
    ]
