# Generated by Django 5.1.15 on 2026-09-01 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_rattraper_factures_payees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_facture'], 'permissions': [('cancel_facture', 'Peut annuler une facture déjà émise')], 'verbose_name': 'facture', 'verbose_name_plural': 'factures'},
        ),
    ]
