# Generated by Django 5.1.15 on 2026-08-19 00:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_user_fonction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'catégorie boutique',
                'verbose_name_plural': 'catégories boutique',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FournisseurBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='contact')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'fournisseur boutique',
                'verbose_name_plural': 'fournisseurs boutique',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='UniteBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'unité boutique',
                'verbose_name_plural': 'unités boutique',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ArticleBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('designation', models.CharField(max_length=200, verbose_name='désignation')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles_boutique', to='core.domaine', verbose_name='domaine d’activité')),
                ('succursale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles_boutique', to='core.succursale', verbose_name='succursale')),
            ],
            options={
                'verbose_name': 'article boutique',
                'verbose_name_plural': 'articles boutique',
                'ordering': ['code'],
                'unique_together': {('code', 'succursale', 'domaine')},
            },
        ),
        migrations.CreateModel(
            name='InventaireBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='numéro')),
                ('date_inventaire', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('portee', models.CharField(choices=[('COMPLET', 'Complet'), ('UN_ARTICLE', 'Un article')], default='COMPLET', max_length=12, verbose_name='portée')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé')], default='BROUILLON', max_length=12, verbose_name='statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventaires_boutique', to='core.domaine', verbose_name='domaine d’activité')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventaires_boutique', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('succursale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventaires_boutique', to='core.succursale', verbose_name='succursale')),
            ],
            options={
                'verbose_name': 'inventaire boutique',
                'verbose_name_plural': 'inventaires boutique',
                'ordering': ['-date_inventaire'],
            },
        ),
        migrations.CreateModel(
            name='SousCategorieBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sous_categories', to='boutique.categorieboutique', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'sous-catégorie boutique',
                'verbose_name_plural': 'sous-catégories boutique',
                'ordering': ['nom'],
                'unique_together': {('categorie', 'code')},
            },
        ),
        migrations.CreateModel(
            name='VarianteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_variante', models.CharField(blank=True, editable=False, max_length=50, verbose_name='code variante')),
                ('genre', models.CharField(blank=True, choices=[('HOMME', 'Homme'), ('FEMME', 'Femme'), ('MIXTE', 'Mixte'), ('ENFANT', 'Enfant')], max_length=10, verbose_name='genre')),
                ('taille', models.CharField(blank=True, max_length=20, verbose_name='taille')),
                ('couleur', models.CharField(blank=True, max_length=30, verbose_name='couleur')),
                ('marque', models.CharField(blank=True, max_length=50, verbose_name='marque')),
                ('matiere', models.CharField(blank=True, max_length=50, verbose_name='matière')),
                ('modele', models.CharField(blank=True, max_length=50, verbose_name='modèle')),
                ('rayon', models.CharField(blank=True, max_length=50, verbose_name='rayon')),
                ('etagere', models.CharField(blank=True, max_length=50, verbose_name='étagère')),
                ('emplacement', models.CharField(blank=True, max_length=50, verbose_name='emplacement')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='prix d’achat')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='prix de vente')),
                ('prix_minimum', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Prix plancher : aucune vente en dessous de ce prix.', max_digits=12, verbose_name='prix minimum')),
                ('prix_maximum', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Prix plafond : aucune vente au-dessus de ce prix.', max_digits=12, verbose_name='prix maximum')),
                ('seuil_alerte', models.PositiveIntegerField(default=0, verbose_name='seuil d’alerte')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=10, verbose_name='statut')),
                ('en_vente', models.BooleanField(default=True, verbose_name='en vente')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='créée le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='boutique.articleboutique', verbose_name='article')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='boutique.categorieboutique', verbose_name='catégorie')),
                ('sous_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='boutique.souscategorieboutique', verbose_name='sous-catégorie')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='boutique.uniteboutique', verbose_name='unité')),
            ],
            options={
                'verbose_name': 'variante d’article',
                'verbose_name_plural': 'variantes d’articles',
                'ordering': ['code_variante'],
                'unique_together': {('article', 'couleur', 'taille', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='StockBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0, verbose_name='quantité')),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks_boutique', to='core.domaine', verbose_name='domaine d’activité')),
                ('succursale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_boutique', to='core.succursale', verbose_name='succursale')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='boutique.variantearticle', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'stock boutique',
                'verbose_name_plural': 'stocks boutique',
                'ordering': ['variante__article__code'],
                'permissions': [('view_stock', 'Peut consulter le stock boutique'), ('adjust_stock', 'Peut ajuster le stock boutique')],
                'unique_together': {('variante', 'succursale', 'domaine')},
            },
        ),
        migrations.CreateModel(
            name='MouvementStockBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement'), ('RETOUR', 'Retour'), ('CASSE', 'Casse'), ('PERTE', 'Perte')], max_length=12, verbose_name='type')),
                ('quantite', models.IntegerField(verbose_name='quantité')),
                ('stock_avant', models.IntegerField(blank=True, null=True, verbose_name='stock avant')),
                ('stock_apres', models.IntegerField(blank=True, null=True, verbose_name='stock après')),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='motif')),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock_boutique', to='core.domaine', verbose_name='domaine d’activité')),
                ('succursale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock_boutique', to='core.succursale', verbose_name='succursale')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock_boutique', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='boutique.stockboutique', verbose_name='stock')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='boutique.variantearticle', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'mouvement de stock boutique',
                'verbose_name_plural': 'mouvements de stock boutique',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='AlerteStockBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STOCK_FAIBLE', 'Stock faible'), ('RUPTURE', 'Rupture')], max_length=12, verbose_name='type')),
                ('seuil', models.PositiveIntegerField(verbose_name='seuil')),
                ('quantite_actuelle', models.IntegerField(verbose_name='quantité actuelle')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLUE', 'Résolue')], default='ACTIVE', max_length=10, verbose_name='statut')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='créée le')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='résolue le')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='boutique.stockboutique', verbose_name='stock')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_stock', to='boutique.variantearticle', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'alerte de stock boutique',
                'verbose_name_plural': 'alertes de stock boutique',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='numéro')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='client')),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('type_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte'), ('AUTRE', 'Autre')], default='ESPECES', max_length=15, verbose_name='paiement')),
                ('montant_recu', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='montant reçu')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=12, verbose_name='statut')),
                ('sous_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='sous-total')),
                ('remise', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='remise')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='total')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='core.domaine', verbose_name='domaine d’activité')),
                ('succursale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='core.succursale', verbose_name='succursale')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'vente',
                'verbose_name_plural': 'ventes',
                'ordering': ['-date_vente'],
                'permissions': [('view_boutique', 'Peut consulter la boutique'), ('create_vente', 'Peut créer une vente'), ('validate_vente', 'Peut valider une vente'), ('cancel_vente', 'Peut annuler une vente'), ('apply_remise', 'Peut appliquer une remise')],
            },
        ),
        migrations.CreateModel(
            name='VenteLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='prix unitaire')),
                ('remise', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='remise')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='total')),
                ('mouvement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligne_vente', to='boutique.mouvementstockboutique', verbose_name='mouvement de sortie')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='boutique.variantearticle', verbose_name='variante')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='boutique.vente', verbose_name='vente')),
            ],
            options={
                'verbose_name': 'ligne de vente',
                'verbose_name_plural': 'lignes de vente',
            },
        ),
        migrations.CreateModel(
            name='LigneInventaireBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_systeme', models.IntegerField(verbose_name='stock système')),
                ('stock_physique', models.IntegerField(verbose_name='stock physique')),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='motif')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='boutique.inventaireboutique', verbose_name='inventaire')),
                ('mouvement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligne_inventaire', to='boutique.mouvementstockboutique', verbose_name='mouvement d’ajustement')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_inventaire', to='boutique.variantearticle', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'ligne d’inventaire boutique',
                'verbose_name_plural': 'lignes d’inventaire boutique',
                'unique_together': {('inventaire', 'variante')},
            },
        ),
    ]
