# Generated by Django 5.1.15 on 2026-08-17 00:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvisionnement', '0008_alter_article_unique_together_and_more'),
        ('core', '0004_user_fonction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_produit', models.CharField(blank=True, max_length=50, verbose_name='type de produit')),
                ('taille', models.CharField(blank=True, max_length=20, verbose_name='taille')),
                ('couleur', models.CharField(blank=True, max_length=30, verbose_name='couleur')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='référence / SKU')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='prix d’achat')),
                ('prix_vente', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='prix de vente')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=10, verbose_name='statut')),
                ('en_vente', models.BooleanField(default=True, verbose_name='en vente')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='infos_boutique', to='approvisionnement.article', verbose_name='article')),
            ],
            options={
                'verbose_name': 'article boutique',
                'verbose_name_plural': 'articles boutique',
                'permissions': [('view_stock', 'Peut consulter le stock boutique'), ('adjust_stock', 'Peut ajuster le stock boutique')],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='numéro')),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('type_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte'), ('AUTRE', 'Autre')], default='ESPECES', max_length=15, verbose_name='paiement')),
                ('montant_recu', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='montant reçu')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=12, verbose_name='statut')),
                ('sous_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='sous-total')),
                ('remise', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='remise')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='total')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='core.domaine', verbose_name='domaine d’activité')),
                ('succursale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='core.succursale', verbose_name='succursale')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'vente',
                'verbose_name_plural': 'ventes',
                'ordering': ['-date_vente'],
                'permissions': [('view_boutique', 'Peut consulter la boutique'), ('create_vente', 'Peut créer une vente'), ('validate_vente', 'Peut valider une vente'), ('cancel_vente', 'Peut annuler une vente'), ('apply_remise', 'Peut appliquer une remise')],
            },
        ),
        migrations.CreateModel(
            name='VenteLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='prix unitaire')),
                ('remise', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='remise')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='total')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='approvisionnement.article', verbose_name='article')),
                ('mouvement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligne_vente', to='approvisionnement.mouvementstock', verbose_name='mouvement de sortie')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='boutique.vente', verbose_name='vente')),
            ],
            options={
                'verbose_name': 'ligne de vente',
                'verbose_name_plural': 'lignes de vente',
            },
        ),
    ]
