# Generated by Django 5.1.15 on 2026-08-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.CharField(blank=True, max_length=200, verbose_name='client'),
        ),
    ]
