# Generated by Django 5.1.15 on 2026-08-19 09:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
        ('core', '0004_user_fonction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articleboutique',
            name='devise',
            field=models.CharField(choices=[('FC', 'Franc congolais (FC)'), ('USD', 'Dollar américain (USD)'), ('EUR', 'Euro (EUR)')], default='FC', max_length=3, verbose_name='devise'),
        ),
        migrations.CreateModel(
            name='BonEntreeBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='numéro')),
                ('genre', models.CharField(blank=True, choices=[('HOMME', 'Homme'), ('FEMME', 'Femme'), ('MIXTE', 'Mixte'), ('ENFANT', 'Enfant')], max_length=10, verbose_name='genre')),
                ('taille', models.CharField(blank=True, max_length=20, verbose_name='taille')),
                ('couleur', models.CharField(blank=True, max_length=30, verbose_name='couleur')),
                ('marque', models.CharField(blank=True, max_length=50, verbose_name='marque')),
                ('modele', models.CharField(blank=True, max_length=50, verbose_name='modèle')),
                ('rayon', models.CharField(blank=True, max_length=50, verbose_name='rayon')),
                ('etagere', models.CharField(blank=True, max_length=50, verbose_name='étagère')),
                ('emplacement', models.CharField(blank=True, max_length=50, verbose_name='emplacement')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='prix d’achat')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='prix de vente')),
                ('prix_minimum', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Prix plancher : aucune vente en dessous de ce prix.', max_digits=12, verbose_name='prix minimum')),
                ('seuil_alerte', models.PositiveIntegerField(default=0, verbose_name='seuil d’alerte')),
                ('quantite', models.PositiveIntegerField(verbose_name='quantité')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé')], default='BROUILLON', max_length=12, verbose_name='statut')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='créé le')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='validé le')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_entree', to='boutique.articleboutique', verbose_name='article')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree', to='boutique.categorieboutique', verbose_name='catégorie')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_entree_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bons_entree_boutique', to='core.domaine', verbose_name='domaine d’activité')),
                ('sous_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree', to='boutique.souscategorieboutique', verbose_name='sous-catégorie')),
                ('succursale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_entree_boutique', to='core.succursale', verbose_name='succursale')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree', to='boutique.uniteboutique', verbose_name='unité')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree_valides', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
            ],
            options={
                'verbose_name': 'entrée en stock',
                'verbose_name_plural': 'entrées en stock',
                'ordering': ['-date_creation'],
                'permissions': [('validate_entree', 'Peut valider une entrée de stock')],
            },
        ),
    ]
