# Generated by Django 5.1.15 on 2026-08-17 00:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleboutique',
            name='prix_limite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Prix plancher : aucune vente en dessous de ce prix.', max_digits=12, verbose_name='prix limite'),
        ),
    ]
