# Generated by Django 5.1.15 on 2026-08-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_articleboutique_devise_bonentreeboutique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonentreeboutique',
            name='couleur',
            field=models.CharField(blank=True, choices=[('Noir', 'Noir'), ('Blanc', 'Blanc'), ('Bleu', 'Bleu'), ('Rouge', 'Rouge'), ('Vert', 'Vert'), ('Jaune', 'Jaune'), ('Gris', 'Gris'), ('Marron', 'Marron'), ('Orange', 'Orange'), ('Rose', 'Rose'), ('Violet', 'Violet'), ('Beige', 'Beige'), ('Multi', 'Multi')], max_length=30, verbose_name='couleur'),
        ),
        migrations.AlterField(
            model_name='bonentreeboutique',
            name='taille',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('U', 'U')], max_length=20, verbose_name='taille'),
        ),
        migrations.AlterField(
            model_name='variantearticle',
            name='couleur',
            field=models.CharField(blank=True, choices=[('Noir', 'Noir'), ('Blanc', 'Blanc'), ('Bleu', 'Bleu'), ('Rouge', 'Rouge'), ('Vert', 'Vert'), ('Jaune', 'Jaune'), ('Gris', 'Gris'), ('Marron', 'Marron'), ('Orange', 'Orange'), ('Rose', 'Rose'), ('Violet', 'Violet'), ('Beige', 'Beige'), ('Multi', 'Multi')], max_length=30, verbose_name='couleur'),
        ),
        migrations.AlterField(
            model_name='variantearticle',
            name='taille',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('U', 'U')], max_length=20, verbose_name='taille'),
        ),
    ]
