# Generated by Django 5.1.15 on 2026-08-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_alter_bonentreeboutique_couleur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PENDING_VALIDATION', 'En attente de validation'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='statut'),
        ),
    ]
