# Generated by Django 5.1.15 on 2026-08-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_alter_vente_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonentreeboutique',
            name='commentaire',
            field=models.CharField(blank=True, help_text='Motif de la décision (annulation) renseigné par le responsable.', max_length=300, verbose_name='commentaire'),
        ),
        migrations.AddField(
            model_name='vente',
            name='commentaire',
            field=models.CharField(blank=True, help_text='Motif de la décision (annulation) renseigné par le responsable.', max_length=300, verbose_name='commentaire'),
        ),
        migrations.AlterField(
            model_name='bonentreeboutique',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ANNULEE', 'Annulé')], default='BROUILLON', max_length=12, verbose_name='statut'),
        ),
    ]
