# Generated by Django 5.1.15 on 2026-08-23 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0008_remove_articleboutique_devise'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTissuArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'type de tissu d’article',
                'verbose_name_plural': 'types de tissus d’articles',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='variantearticle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bonentreeboutique',
            name='type_tissu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree', to='boutique.typetissuarticle', verbose_name='type de tissu'),
        ),
        migrations.AddField(
            model_name='variantearticle',
            name='type_tissu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='boutique.typetissuarticle', verbose_name='type de tissu'),
        ),
        migrations.AddConstraint(
            model_name='variantearticle',
            constraint=models.UniqueConstraint(condition=models.Q(('type_tissu__isnull', True)), fields=('article', 'couleur', 'taille', 'genre'), name='variante_unique_sans_tissu'),
        ),
        migrations.AddConstraint(
            model_name='variantearticle',
            constraint=models.UniqueConstraint(condition=models.Q(('type_tissu__isnull', False)), fields=('article', 'couleur', 'taille', 'genre', 'type_tissu'), name='variante_unique_avec_tissu'),
        ),
    ]
