# Generated by Django 5.1.15 on 2026-08-26 08:45

from decimal import Decimal
from django.db import migrations, models


def backfill_prix_propose(apps, schema_editor):
    """Les lignes existantes sont facturées au prix normal : prix_propose = prix_unitaire."""
    VenteLigne = apps.get_model('boutique', 'VenteLigne')
    VenteLigne.objects.filter(prix_propose__isnull=True).update(
        prix_propose=models.F('prix_unitaire'))


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0009_typetissuarticle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venteligne',
            name='prix_propose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='prix proposé'),
        ),
        migrations.AlterField(
            model_name='venteligne',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='prix unitaire normal'),
        ),
        migrations.RunPython(backfill_prix_propose, migrations.RunPython.noop),
    ]
