# Generated by Django 5.1.15 on 2026-08-28 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0010_venteligne_prix_propose_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venteligne',
            name='date_decision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='décidé le'),
        ),
        migrations.AddField(
            model_name='venteligne',
            name='decide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_decidees', to=settings.AUTH_USER_MODEL, verbose_name='décidé par'),
        ),
        migrations.AddField(
            model_name='venteligne',
            name='prix_responsable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='prix retenu par le responsable'),
        ),
        migrations.AddField(
            model_name='venteligne',
            name='statut_ligne',
            field=models.CharField(choices=[('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='VALIDEE', max_length=12, verbose_name='statut de la ligne'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PENDING_VALIDATION', 'En attente de traitement'), ('TRAITEE', 'Traitée'), ('VALIDEE', 'Validée'), ('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='statut'),
        ),
    ]
