# Generated by Django 5.1.15 on 2026-08-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0012_venteligne_statut_rejete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venteligne',
            name='statut_ligne',
            field=models.CharField(choices=[('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='VALIDEE', max_length=12, verbose_name='statut de la ligne'),
        ),
    ]
