# Generated by Django 5.1.15 on 2026-08-30 17:42

import django.db.models.deletion
from django.db import migrations, models


def creer_etageres_defaut(apps, schema_editor):
    EtagereBoutique = apps.get_model('boutique', 'EtagereBoutique')
    EmplacementBoutique = apps.get_model('boutique', 'EmplacementBoutique')
    if EtagereBoutique.objects.exists():
        return
    for et_code, et_nom, emps in (
        ('ETA', 'Étagère A', (('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'))),
        ('ETB', 'Étagère B', (('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'))),
    ):
        etagere = EtagereBoutique.objects.create(code=et_code, nom=et_nom)
        for emp_code, emp_nom in emps:
            EmplacementBoutique.objects.create(
                etagere=etagere, code=emp_code, nom=emp_nom,
            )


def supprimer_etageres_defaut(apps, schema_editor):
    EtagereBoutique = apps.get_model('boutique', 'EtagereBoutique')
    EmplacementBoutique = apps.get_model('boutique', 'EmplacementBoutique')
    EmplacementBoutique.objects.filter(
        etagere__code__in=('ETA', 'ETB')).delete()
    EtagereBoutique.objects.filter(code__in=('ETA', 'ETB')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0013_alter_venteligne_statut_ligne'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtagereBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'étagère boutique',
                'verbose_name_plural': 'étagères boutique',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='uniteboutique',
            options={'ordering': ['nom'], 'verbose_name': 'unité boutique', 'verbose_name_plural': 'unités boutique'},
        ),
        migrations.CreateModel(
            name='EmplacementBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('etagere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emplacements', to='boutique.etagereboutique', verbose_name='étagère')),
            ],
            options={
                'verbose_name': 'emplacement boutique',
                'verbose_name_plural': 'emplacements boutique',
                'ordering': ['etagere__nom', 'nom'],
                'unique_together': {('etagere', 'code')},
            },
        ),
        migrations.RunPython(creer_etageres_defaut, supprimer_etageres_defaut),
    ]
