# Generated by Django 5.1.15 on 2026-09-01 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0014_etagere_emplacement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonentreeboutique',
            options={'ordering': ['-date_creation'], 'permissions': [('validate_entree', 'Peut valider une entrée de stock'), ('cancel_entree', 'Peut annuler une entrée de stock')], 'verbose_name': 'entrée en stock', 'verbose_name_plural': 'entrées en stock'},
        ),
    ]
