# Generated by Django 5.1.15 on 2026-09-02 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0015_profils_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonentreeboutique',
            name='variante',
            field=models.ForeignKey(blank=True, help_text='Renseignée pour un réapprovisionnement : la validation n’ajoute que du stock.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bons_entree', to='boutique.variantearticle', verbose_name='variante existante'),
        ),
    ]
